[package]
name = "ipset"
version = "0.7.2"
edition = "2021"
license = "MIT"
description = "A wrapper for libipset"
repository = "https://github.com/lazytiger/ipset"
links = "ipset"

[dependencies]
libc = "0.2"
derive_more = "0.99"
ipset_derive = "0.1"

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
